#define	STRANGE_OBJECT	0
#define	AMULET_OF_YENDOR	1
#define	FOOD_RATION	2
#define	TRIPE_RATION	3
#define	PANCAKE	4
#define	DEAD_LIZARD	5
#define	FORTUNE_COOKIE	6
#define	CARROT	7
#define	SLICE_OF_PIZZA	8
#define	CREAM_PIE	9
#define	TIN	10
#define	ORANGE	11
#define	APPLE	12
#define	PEAR	13
#define	MELON	14
#define	BANANA	15
#define	CANDY_BAR	16
#define	EGG	17
#define	CLOVE_OF_GARLIC	18
#define	LUMP_OF_ROYAL_JELLY	19
#define	DEAD_HUMAN	20
#define	DEAD_GIANT_ANT	21
#define	DEAD_GIANT_BAT	22
#define	DEAD_CENTAUR	23
#define	DEAD_DRAGON	24
#define	DEAD_FLOATING_EYE	25
#define	DEAD_FREEZING_SPHERE	26
#define	DEAD_GNOME	27
#define	DEAD_HOBGOBLIN	28
#define	DEAD_STALKER	29
#define	DEAD_JACKAL	30
#define	DEAD_KOBOLD	31
#define	DEAD_LEPRECHAUN	32
#define	DEAD_MIMIC	33
#define	DEAD_NYMPH	34
#define	DEAD_ORC	35
#define	DEAD_PURPLE_WORM	36
#define	DEAD_QUANTUM_MECHANIC	37
#define	DEAD_RUST_MONSTER	38
#define	DEAD_SNAKE	39
#define	DEAD_TROLL	40
#define	DEAD_UMBER_HULK	41
#define	DEAD_VAMPIRE	42
#define	DEAD_WRAITH	43
#define	DEAD_XORN	44
#define	DEAD_YETI	45
#define	DEAD_ZOMBIE	46
#define	DEAD_ACID_BLOB	47
#define	DEAD_GIANT_BEETLE	48
#define	DEAD_COCKATRICE	49
#define	DEAD_DOG	50
#define	DEAD_ETTIN	51
#define	DEAD_FOG_CLOUD	52
#define	DEAD_GELATINOUS_CUBE	53
#define	DEAD_HOMUNCULUS	54
#define	DEAD_IMP	55
#define	DEAD_JAGUAR	56
#define	DEAD_KILLER_BEE	57
#define	DEAD_LEOCROTTA	58
#define	DEAD_MINOTAUR	59
#define	DEAD_NURSE	60
#define	DEAD_OWLBEAR	61
#define	DEAD_PIERCER	62
#define	DEAD_QUIVERING_BLOB	63
#define	DEAD_GIANT_RAT	64
#define	DEAD_GIANT_SCORPION	65
#define	DEAD_TENGU	66
#define	DEAD_UNICORN	67
#define	DEAD_VIOLET_FUNGUS	68
#define	DEAD_LONG_WORM	69
#define	DEAD_XAN	70
#define	DEAD_YELLOW_LIGHT	71
#define	DEAD_ZRUTY	72
#define	DEAD_GIANT	73
#define	DEAD_DEMON	74
#define	ARROW	75
#define	SLING_BULLET	76
#define	CROSSBOW_BOLT	77
#define	DART	78
#define	SHURIKEN	79
#define	ROCK	80
#define	BOOMERANG	81
#define	MACE	82
#define	AXE	83
#define	FLAIL	84
#define	LONG_SWORD	85
#define	TWO_HANDED_SWORD	86
#define	DAGGER	87
#define	WORM_TOOTH	88
#define	CRYSKNIFE	89
#define	AKLYS	90
#define	BARDICHE	91
#define	BEC_DE_CORBIN	92
#define	BILL_GUISARME	93
#define	CLUB	94
#define	FAUCHARD	95
#define	GLAIVE	96
#define	GUISARME	97
#define	HALBERD	98
#define	LUCERN_HAMMER	99
#define	JAVELIN	100
#define	KATANA	101
#define	LANCE	102
#define	MORNING_STAR	103
#define	PARTISAN	104
#define	RANSEUR	105
#define	SCIMITAR	106
#define	SPETUM	107
#define	BROAD_SWORD	108
#define	SHORT_SWORD	109
#define	TRIDENT	110
#define	VOULGE	111
#define	SPEAR	112
#define	BOW	113
#define	SLING	114
#define	CROSSBOW	115
#define	WHISTLE	116
#define	LEASH	117
#define	MAGIC_WHISTLE	118
#define	EXPENSIVE_CAMERA	119
#define	ICE_BOX	120
#define	PICK_AXE	121
#define	MAGIC_MARKER	122
#define	STETHOSCOPE	123
#define	CAN_OPENER	124
#define	HEAVY_IRON_BALL	125
#define	IRON_CHAIN	126
#define	ENORMOUS_ROCK	127
#define	HELMET	128
#define	PLATE_MAIL	129
#define	SPLINT_MAIL	130
#define	BANDED_MAIL	131
#define	CHAIN_MAIL	132
#define	SCALE_MAIL	133
#define	RING_MAIL	134
#define	STUDDED_LEATHER_ARMOR	135
#define	ELFIN_CHAIN_MAIL	136
#define	BRONZE_PLATE_MAIL	137
#define	CRYSTAL_PLATE_MAIL	138
#define	LEATHER_ARMOR	139
#define	ELVEN_CLOAK	140
#define	SHIELD	141
#define	PAIR_OF_GLOVES	142
#define	POT_RESTORE_STRENGTH	143
#define	POT_GAIN_ENERGY	144
#define	POT_BOOZE	145
#define	POT_INVISIBILITY	146
#define	POT_FRUIT_JUICE	147
#define	POT_HEALING	148
#define	POT_PARALYSIS	149
#define	POT_MONSTER_DETECTION	150
#define	POT_OBJECT_DETECTION	151
#define	POT_SICKNESS	152
#define	POT_CONFUSION	153
#define	POT_GAIN_STRENGTH	154
#define	POT_SPEED	155
#define	POT_BLINDNESS	156
#define	POT_GAIN_LEVEL	157
#define	POT_EXTRA_HEALING	158
#define	POT_LEVITATION	159
#define	POT_HALLUCINATION	160
#define	POT_HOLY_WATER	161
#define	SCR_MAIL	164
#define	SCR_ENCHANT_ARMOR	165
#define	SCR_DESTROY_ARMOR	166
#define	SCR_CONFUSE_MONSTER	167
#define	SCR_SCARE_MONSTER	168
#define	SCR_BLANK_PAPER	169
#define	SCR_REMOVE_CURSE	170
#define	SCR_ENCHANT_WEAPON	171
#define	SCR_DAMAGE_WEAPON	172
#define	SCR_CREATE_MONSTER	173
#define	SCR_TAMING	174
#define	SCR_GENOCIDE	175
#define	SCR_LIGHT	176
#define	SCR_TELEPORTATION	177
#define	SCR_GOLD_DETECTION	178
#define	SCR_FOOD_DETECTION	179
#define	SCR_IDENTIFY	180
#define	SCR_MAGIC_MAPPING	181
#define	SCR_AMNESIA	182
#define	SCR_FIRE	183
#define	SCR_PUNISHMENT	184
#define	WAN_LIGHT	189
#define	WAN_SECRET_DOOR_DETECTION	190
#define	WAN_CREATE_MONSTER	191
#define	WAN_WISHING	192
#define	WAN_STRIKING	193
#define	WAN_NOTHING	194
#define	WAN_SLOW_MONSTER	195
#define	WAN_SPEED_MONSTER	196
#define	WAN_UNDEAD_TURNING	197
#define	WAN_POLYMORPH	198
#define	WAN_CANCELLATION	199
#define	WAN_TELEPORTATION	200
#define	WAN_MAKE_INVISIBLE	201
#define	WAN_PROBING	202
#define	WAN_DIGGING	203
#define	WAN_MAGIC_MISSILE	204
#define	WAN_FIRE	205
#define	WAN_SLEEP	206
#define	WAN_COLD	207
#define	WAN_DEATH	208
#define	SPE_MAGIC_MISSILE	211
#define	SPE_FIREBALL	212
#define	SPE_SLEEP	213
#define	SPE_CONE_OF_COLD	214
#define	SPE_FINGER_OF_DEATH	215
#define	SPE_HEALING	216
#define	SPE_DETECT_MONSTERS	217
#define	SPE_FORCE_BOLT	218
#define	SPE_LIGHT	219
#define	SPE_CONFUSE_MONSTER	220
#define	SPE_CURE_BLINDNESS	221
#define	SPE_SLOW_MONSTER	222
#define	SPE_CREATE_MONSTER	223
#define	SPE_DETECT_FOOD	224
#define	SPE_HASTE_SELF	225
#define	SPE_CAUSE_FEAR	226
#define	SPE_CURE_SICKNESS	227
#define	SPE_DETECT_UNSEEN	228
#define	SPE_EXTRA_HEALING	229
#define	SPE_CHARM_MONSTER	230
#define	SPE_LEVITATION	231
#define	SPE_RESTORE_STRENGTH	232
#define	SPE_INVISIBILITY	233
#define	SPE_DETECT_TREASURE	234
#define	SPE_DIG	235
#define	SPE_REMOVE_CURSE	236
#define	SPE_MAGIC_MAPPING	237
#define	SPE_IDENTIFY	238
#define	SPE_TURN_UNDEAD	239
#define	SPE_POLYMORPH	240
#define	SPE_CREATE_FAMILIAR	241
#define	SPE_TELEPORT_AWAY	242
#define	SPE_CANCELLATION	243
#define	SPE_GENOCIDE	244
#define	Adornment	u.uprops[0].p_flgs
#define	RIN_ADORNMENT	249
#define	HTeleportation	u.uprops[1].p_flgs
#define	Teleportation	((HTeleportation) || index("LNt", u.usym))
#define	RIN_TELEPORTATION	250
#define	HRegeneration	u.uprops[2].p_flgs
#define	Regeneration	((HRegeneration) || index("TVi", u.usym))
#define	RIN_REGENERATION	251
#define	Searching	u.uprops[3].p_flgs
#define	RIN_SEARCHING	252
#define	HSee_invisible	u.uprops[4].p_flgs
#define	See_invisible	((HSee_invisible) || index("I", u.usym))
#define	RIN_SEE_INVISIBLE	253
#define	Stealth	u.uprops[5].p_flgs
#define	RIN_STEALTH	254
#define	Levitation	u.uprops[6].p_flgs
#define	RIN_LEVITATION	255
#define	HPoison_resistance	u.uprops[7].p_flgs
#define	Poison_resistance	((HPoison_resistance) || index("abcghikqsuvxyADFQSVWXZ&", u.usym))
#define	RIN_POISON_RESISTANCE	256
#define	Aggravate_monster	u.uprops[8].p_flgs
#define	RIN_AGGRAVATE_MONSTER	257
#define	Hunger	u.uprops[9].p_flgs
#define	RIN_HUNGER	258
#define	HFire_resistance	u.uprops[10].p_flgs
#define	Fire_resistance	((HFire_resistance) || index("gD&", u.usym))
#define	RIN_FIRE_RESISTANCE	259
#define	HCold_resistance	u.uprops[11].p_flgs
#define	Cold_resistance	((HCold_resistance) || index("gFY", u.usym))
#define	RIN_COLD_RESISTANCE	260
#define	Protection_from_shape_changers	u.uprops[12].p_flgs
#define	RIN_PROTECTION_FROM_SHAPE_CHAN	261
#define	Conflict	u.uprops[13].p_flgs
#define	RIN_CONFLICT	262
#define	Gain_strength	u.uprops[14].p_flgs
#define	RIN_GAIN_STRENGTH	263
#define	Increase_damage	u.uprops[15].p_flgs
#define	RIN_INCREASE_DAMAGE	264
#define	Protection	u.uprops[16].p_flgs
#define	RIN_PROTECTION	265
#define	Warning	u.uprops[17].p_flgs
#define	RIN_WARNING	266
#define	HTeleport_control	u.uprops[18].p_flgs
#define	Teleport_control	((HTeleport_control) || index("t", u.usym))
#define	RIN_TELEPORT_CONTROL	267
#define	DILITHIUM_CRYSTAL	270
#define	DIAMOND	271
#define	RUBY	272
#define	SAPPHIRE	273
#define	EMERALD	274
#define	TURQUOISE	275
#define	AQUAMARINE	276
#define	TOURMALINE	277
#define	TOPAZ	278
#define	OPAL	279
#define	GARNET	280
#define	AMETHYST	281
#define	AGATE	282
#define	ONYX	283
#define	JASPER	284
#define	JADE	285
/* #define	WORTHLESS_PIECE_OF_BLUE_GLASS	286 */
/* #define	WORTHLESS_PIECE_OF_RED_GLASS	287 */
/* #define	WORTHLESS_PIECE_OF_YELLOW_GLASS	288 */
/* #define	WORTHLESS_PIECE_OF_GREEN_GLASS	289 */

#define	CORPSE		DEAD_HUMAN
#define	DEAD_KOP		DEAD_KOBOLD
#define	DEAD_GIANT_SPIDER	DEAD_GIANT_SCORPION
#define	DEAD_ROCKMOLE		DEAD_GIANT_RAT
#define	LAST_GEM	(JADE+1)
#define	LAST_RING	19
#define MAXSPELL	35
#define	NROFOBJECTS	289
